version: '3'
services:
  nginx:
    container_name: nginx3
    image: nginx
    ports:
      - 20080:80
    volumes:
      - ./server:/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    container_name: php3
    build: .
    volumes:
      - ./server:/src
    working_dir: /src/laravel

  mysql:
    container_name: mysql3
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33306:3306